use sed entirely with regex to get the java major version
pinterest/ktlint pull request #1544
Opened 2022-07-13 19:20 UTC by rawilder

## Description

Fix java version being incorrectly set when JAVA_TOOL_OPTIONS has a value. A couple of tests failed locally but the same tests failed on master for me locally.

```
CLI basic checks > Given CLI argument --help then return the help output() FAILED
    org.opentest4j.AssertionFailedError at SimpleCLITest.kt:14

CLI basic checks > Given CLI argument --version then return the version information output() FAILED
    org.opentest4j.AssertionFailedError at SimpleCLITest.kt:29

CLI basic checks > Given some code without errors then return from lint with normal exit code and no error output() FAILED
    org.opentest4j.AssertionFailedError at SimpleCLITest.kt:45

```

## Checklist

- [x] PR description added
- [ ] tests are added // is this something I can test considering it is in the build execution itself?
- [x] `CHANGELOG.md` is updated

2022-07-14 19:02 UTC, paul-dingemans requested changes

2022-07-14 19:02 UTC, paul-dingemans commented on ktlint/build.gradle.kts
> +        execFile.appendText("#!/bin/sh\n\nJV=\$(java -version 2>&1 | sed -E -n 's/.* version \"([^.-]*).*\".*/\\1/p')\n\nX=\$( [ \"\$JV\" -ge \"16\" ] && echo \"--add-opens java.base/java.lang=ALL-UN
Can you explain why the old command failed on your system? Is it for example running on MS Windows? If so, please add some OS specific tests which will ensure that the same problem does not re-occur in the future.

2022-07-14 19:04 UTC, paul-dingemans commented
I am just reading the issue #1544 after making my review remarks. That issue clarifies already a lot.

2022-07-14 20:33 UTC, rawilder commented
Would you like me to update the PR description with text from the issue to make it clearer what this is doing?

2022-07-17 19:31 UTC, paul-dingemans commented
> Would you like me to update the PR description with text from the issue to make it clearer what this is doing?

That would have helped with the initial review. It would be great if you can still update it though for future reference.

2022-07-18 18:14 UTC, rawilder commented
Updated description with more info.

2022-07-21 18:53 UTC, paul-dingemans approved these changes

2022-07-21 18:54 UTC, merged