Fix links in documentation
pinterest/ktlint pull request #1588
Opened 2022-08-16 15:45 UTC by eboudrant

Indentation made the paragraph a code block causing the link to not work, removed indent.

2022-08-16 16:41 UTC, Goooler approved these changes

2022-08-17 16:49 UTC, paul-dingemans requested changes

2022-08-17 18:04 UTC, eboudrant commented on docs/rules/configuration-ktlint.md
> +Unfortunately [IntelliJ IDEA](https://www.jetbrains.com/idea/) has an [autoformat issue regarding `.editorconfig`](https://youtrack.jetbrains.com/issue/IDEA-242506). Due to this error an additional s
Ah, I don't see the danger box, I use OSX 12.5 / Chrome. I see this when I open the md:

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/773377/185210719-9dee644b-1643-45e2-92f2-7323166833ec.png">

2022-08-17 18:06 UTC, eboudrant commented on docs/rules/configuration-ktlint.md
> +Unfortunately [IntelliJ IDEA](https://www.jetbrains.com/idea/) has an [autoformat issue regarding `.editorconfig`](https://youtrack.jetbrains.com/issue/IDEA-242506). Due to this error an additional s
Ok, I see what the problem, github markdown do not recognize the danger box (but the [website](https://pinterest.github.io/) documentation do), sorry for confusion, I think I can close the PR.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/773377/185211069-33fca7b0-c953-4034-bfb1-cb17d0f29c6b.png">

2022-08-17 18:11 UTC, closed without merging