Update ImportOrdering to explain pointer
pinterest/ktlint pull request #1612
Opened 2022-08-26 14:11 UTC by blundell

## Description

The import ordering rule always points to the first line of the import block.

This always seems to confuse people into thinking it's pointing at the line which is at fault. (it's not)

Expand the error message to explain that the error is somewhere in the whole imports block.

![image](https://user-images.githubusercontent.com/655860/186922817-83372dda-ce57-4940-b3ad-e5d2875b5756.png)

## Checklist

- [ ] PR description added
- [ ] tests are added
- [ ] KtLint has been applied on source code itself and violations are fixed
- [ ] [documentation](https://pinterest.github.io/ktlint/) is updated
- [ ] `CHANGELOG.md` is updated

In case of adding a new rule:
- [ ] Rule is added to [rules documentation](https://pinterest.github.io/ktlint/rules/standard/)

2022-08-27 14:21 UTC, paul-dingemans commented
Thx for trying to improve ktlint. I do not think that the error message should be changed as proposed. Main reason is that it should not be that hard to determine the correct (or least a better offset). In method below the expected and actual imports are compared:
```
    private fun importsAreEqual(actual: List<ASTNode>, expected: List<ASTNode>): Boolean {
        if (actual.size != expected.size) return false

        val combined = actual.zip(expected)
        return combined.all { (first, second) ->
            if (first is PsiWhiteSpace && second is PsiWhiteSpace) {
                return@all (first as PsiWhiteSpace).text == (second as PsiWhiteSpace).text
            }
            return@all first == second
        }
    }
```
The first import for which the actual import is not equal to the expected import should be the line that needs to be reported.

Would you mind to try to try above?

2022-08-27 15:54 UTC, paul-dingemans requested changes
Thx for trying to improve ktlint. I do not think that the error message should be changed as proposed. Main reason is that it should not be that hard to determine the correct (or least a better offset). In method below the expected and actual imports are compared:

    private fun importsAreEqual(actual: List<ASTNode>, expected: List<ASTNode>): Boolean {
        if (actual.size != expected.size) return false

        val combined = actual.zip(expected)
        return combined.all { (first, second) ->
            if (first is PsiWhiteSpace && second is PsiWhiteSpace) {
                return@all (first as PsiWhiteSpace).text == (second as PsiWhiteSpace).text
            }
            return@all first == second
        }
    }
The first import for which the actual import is not equal to the expected import should be the line that needs to be reported.

Would you mind to try to try above?

2022-08-29 08:21 UTC, blundell commented
@paul-dingemans what if there are multiple ordering errors, pointing at one of them could also lead to confusion as its not pointing to all the errors. I assume this may be some of the reason why it just points to the whole block.

2022-08-29 14:44 UTC, paul-dingemans commented
Yes, in case of multiple errors it can still be confusing but at least you are directed to the first wrong line. After fixing it, the line number at least will be increased.

2022-09-18 11:07 UTC, paul-dingemans commented
@blundell Please create a new PR if you want to improve the error message as I suggested before.

2022-09-18 11:07 UTC, closed without merging