Change rule description
pinterest/ktlint pull request #2079
Opened 2023-06-13 04:49 UTC by avinash3699

Changed the rule description of Rule id: enum-entry-name-case. 
The rule allows to have upper camel-case separated enum names, but not mentioned in the documentation. Hence, added that for clear understanding for the users.

2023-06-13 16:26 UTC, paul-dingemans requested changes

2023-06-13 16:26 UTC, paul-dingemans commented on documentation/release-latest/docs/rules/standard.md
> +Enum entry names should be uppercase underscore-separated or upper camel-case separated.
Please, also add `FooBar` as allowed example.

2023-06-13 16:26 UTC, paul-dingemans commented on documentation/snapshot/docs/rules/standard.md
> +Enum entry names should be uppercase underscore-separated or upper camel-case separated.
Please, also add `FooBar` as allowed example.

2023-06-14 04:36 UTC, avinash3699 commented
Added

2023-06-14 07:59 UTC, avinash3699 commented on documentation/release-latest/docs/rules/standard.md
> +Enum entry names should be uppercase underscore-separated or upper camel-case separated.
Done

2023-06-14 17:58 UTC, merged