Set and reset Locale to pass test for non-english contributor.
pinterest/ktlint pull request #2622
Opened 2024-04-01 00:55 UTC by Jaehwa-Noh

## Description
When I build code on local machine, some tests failed because of current language setting.
See this issue.
Fixes #2621 

Then I temporary set the default language from Default to English.
 
## Checklist

Before submitting the PR, please check following (checks which are not relevant may be ignored):
- [x] Commit message are well written. In addition to a short title, the commit message also explain why a change is made.
- [ ] At least one commit message contains a reference `Closes #<xxx>` or `Fixes #<xxx>` (replace`<xxx>` with issue number)
- [ ] Tests are added
- [ ] KtLint format has been applied on source code itself and violations are fixed
- [ ] PR title is short and clear (it is used as description in the release changelog)
- [ ] PR description added (background information)

[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release documentation](https://github.com/pinterest/ktlint/tree/master/documentation)
- [ ] [Snapshot documentation](https://github.com/pinterest/ktlint/tree/master/documentation/snapshot) in case documentation is to be released together with a code change
- [ ] [Release documentation](https://github.com/pinterest/ktlint/tree/master/documentation/release-latest) in case documentation is related to a released version of ktlint and has to be published as soon as the change is merged to master

2024-04-01 11:01 UTC, paul-dingemans requested changes
Tnx for reporting an fixing. Please address the remarks.

2024-04-01 11:01 UTC, paul-dingemans commented on ktlint-cli-reporter-baseline/src/test/kotlin/com/pinterest/ktlint/cli/reporter/baseline/BaselineTest.kt
> +        private fun resetLocale(default: Locale) = Locale.setDefault(default)
When code is moved to BeforeEach and AfterEach, it is not necessary those helper methods. It is pretty obvious what is done.

2024-04-01 11:23 UTC, Jaehwa-Noh commented
Thank you for reviewing.
I'd changed what you addressed.

2024-04-06 18:37 UTC, merged

2024-04-06 18:37 UTC, paul-dingemans commented
Tnx for your contribution